apiVersion: v1
kind: Service
metadata:
  name: codex-backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: 4000
  selector:
    app: codex-backend
