apiVersion: apps/v1
kind: Deployment
metadata:
  name: codex-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codex-frontend
  template:
    metadata:
      labels:
        app: codex-frontend
    spec:
      imagePullSecrets:
        {{- if .Values.imagePullSecrets }}
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
        {{- end }}
      containers:
        - name: codex-frontend
          image: {{ .Values.image.codexFrontend }}
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: codex-fe-secret

