{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codex-job-creator-binding
  namespace: codex-stage
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: codex-stage
roleRef:
  name: codex-sa-role
  apiGroup: rbac.authorization.k8s.io
  kind: Role
{{- end }}